### ISSUE TITLE
2.4G与5G调整

### ISSUE THREAD

**Issue by nealwx** [paldier/K3C-merlin#1]
从恩山上面看到了问题，如果只是想调整wlan0 和 wlan2 对应的2.4G 和 5G 的顺序的话，其实只要改动router/rc/init.c:8069 行为nvram_set("wl_ifnames", "wlan2 wlan0"); 即可。
我简单看了一下源码，有关2.4G 和 5G 对应的power 部分可能还要再进行调整
由于手头上没有机子，无法进行验证。
希望以上信息能够对你有所帮助

**Comment by paldier** [comment]
nvram不会干涉顺序问题，包括 api-lantiq里面的顺序都不会干涉系统生成接口名顺序

**Comment by nealwx** [comment]
从恩山上看到的描述，我的理解是2.4G 和 5G 所以绑定的interface错掉了，所以我才会提出说更改这个nvram的顺序

**Comment by nealwx** [comment]
如果你是希望wlan0 和 wlan2 所对的硬件接口变化的话，那我就没辙了。对于asuswrt 来说，相对简单的方法就是改变其2.4G和5G所对应的interface了

**Comment by paldier** [comment]
不用硬件接口变化，只需要wlan0和wlan2互调一下就行，但是nvram实现不了

**Comment by nealwx** [comment]
我理解你的意思了，也就是说再K3C 上wlan0 实际对应到的是5G， 而wlan2 对应到是2.4G？
在Bluecave上wlan0 对应是2,4G wlan2 对应的是5G。
我不建议你在系统底层上去将wlan0 和 wlan2去互换，如果没有一定的经验话，去动系统底层反而会比较耗时耗力。
而改动nvram 顺序是可以在启动无线时将2.4G给自动绑定到wlan2上 5G绑到wlan0上。

**Comment by paldier** [comment]
nvram实现不了，wlan0是驱动接受第一个pcie设备分配的

**Comment by paldier** [comment]
测试的结果也是无效的
