### ISSUE TITLE
C1 compatibility

### ISSUE THREAD

**Issue by SirLouen** [paldier/K3C-merlin#2]
Hello
I've recently received a K3C with HW c1 and I see it's not supported.
What differences have you found between C1 and the rest of the models?

**Comment by paldier** [comment]
i guess C1=B2
and  B1/B1G/A1 need a special single daughter board for 384+

[200951ubdij0i99o94zz99.jpg](https://www.right.com.cn/FORUM/data/attachment/forum/201812/04/200951ubdij0i99o94zz99.jpg)
https://wikidevi.com/wiki/Phicomm_K3C

**Comment by SirLouen** [comment]
I'm not sure. I'm thinking on returning it because I've found that the default firmware lacks of all the basic routing functionality such as configuring the router as a simple bridged AP...

I have not opened (it's still on 30 day return), and I don't want to break it. But from the back I see it has similar config that the one you put in the image:

![image](https://user-images.githubusercontent.com/224787/51077674-0c697500-16aa-11e9-8719-3c9505b69e06.png)

**Comment by SirLouen** [comment]
I've been trying to open the case, but I cannot find any screw. I thought there was a screw under the bottom sticker but there isn't. Any ideas to open it and see the motherboard configuration of the C1?
