### ISSUE TITLE
请教一下编译梅林固件时怎样修改默认SSID

### ISSUE THREAD

**Issue by geoleonsh** [paldier/K3C-merlin#4]
大神，请教一下编译梅林固件时怎样修改默认SSID，即将默认的ssid:ASUS和ASUS_5G改为其它。

还有我在适配K3C的时候，merlinwrt编译后aimesh没有，跟踪到state.js然后再跟踪到get_ui_support函数，就不知道咋办了，烦请指点一下，谢谢啦

**Comment by paldier** [comment]
你想要的东西自己联系华硕，想叫我提供也可以，3个亿
